# Cristiano Ronaldo winking face - cloud in the sky
# Generated by generators/face_to_mcfunction.py

fill ~-7 ~109 ~40 ~5 ~109 ~40 brown_concrete
fill ~-10 ~108 ~40 ~-8 ~108 ~40 brown_concrete
fill ~-7 ~108 ~40 ~-6 ~108 ~40 black_concrete
fill ~-5 ~108 ~40 ~2 ~108 ~40 brown_concrete
fill ~3 ~108 ~40 ~4 ~108 ~40 black_concrete
fill ~5 ~108 ~40 ~7 ~108 ~40 brown_concrete
fill ~-12 ~107 ~40 ~-11 ~107 ~40 brown_concrete
fill ~-10 ~107 ~40 ~-9 ~107 ~40 black_concrete
fill ~-8 ~107 ~40 ~-7 ~107 ~40 brown_concrete
fill ~-6 ~107 ~40 ~-5 ~107 ~40 black_concrete
fill ~-4 ~107 ~40 ~1 ~107 ~40 brown_concrete
fill ~2 ~107 ~40 ~3 ~107 ~40 black_concrete
fill ~4 ~107 ~40 ~5 ~107 ~40 brown_concrete
fill ~6 ~107 ~40 ~7 ~107 ~40 black_concrete
fill ~8 ~107 ~40 ~9 ~107 ~40 brown_concrete
setblock ~-13 ~106 ~40 brown_concrete
fill ~-12 ~106 ~40 ~-11 ~106 ~40 black_concrete
fill ~-10 ~106 ~40 ~-6 ~106 ~40 brown_concrete
fill ~-5 ~106 ~40 ~-4 ~106 ~40 black_concrete
fill ~-3 ~106 ~40 ~0 ~106 ~40 brown_concrete
fill ~1 ~106 ~40 ~2 ~106 ~40 black_concrete
fill ~3 ~106 ~40 ~7 ~106 ~40 brown_concrete
fill ~8 ~106 ~40 ~9 ~106 ~40 black_concrete
setblock ~10 ~106 ~40 brown_concrete
setblock ~-14 ~105 ~40 brown_concrete
setblock ~-13 ~105 ~40 black_concrete
fill ~-12 ~105 ~40 ~-5 ~105 ~40 brown_concrete
fill ~-4 ~105 ~40 ~-3 ~105 ~40 black_concrete
fill ~-2 ~105 ~40 ~-1 ~105 ~40 brown_concrete
fill ~0 ~105 ~40 ~1 ~105 ~40 black_concrete
fill ~2 ~105 ~40 ~9 ~105 ~40 brown_concrete
setblock ~10 ~105 ~40 black_concrete
setblock ~11 ~105 ~40 brown_concrete
setblock ~-15 ~104 ~40 brown_concrete
setblock ~-14 ~104 ~40 black_concrete
fill ~-13 ~104 ~40 ~-4 ~104 ~40 brown_concrete
setblock ~-3 ~104 ~40 black_concrete
fill ~-2 ~104 ~40 ~-1 ~104 ~40 brown_concrete
setblock ~0 ~104 ~40 black_concrete
fill ~1 ~104 ~40 ~10 ~104 ~40 brown_concrete
setblock ~11 ~104 ~40 black_concrete
setblock ~12 ~104 ~40 brown_concrete
setblock ~-16 ~103 ~40 brown_concrete
setblock ~-15 ~103 ~40 black_concrete
fill ~-14 ~103 ~40 ~-4 ~103 ~40 brown_concrete
fill ~-3 ~103 ~40 ~0 ~103 ~40 black_concrete
fill ~1 ~103 ~40 ~11 ~103 ~40 brown_concrete
setblock ~12 ~103 ~40 black_concrete
setblock ~13 ~103 ~40 brown_concrete
setblock ~-17 ~102 ~40 brown_concrete
setblock ~-16 ~102 ~40 black_concrete
fill ~-15 ~102 ~40 ~-3 ~102 ~40 brown_concrete
fill ~-2 ~102 ~40 ~-1 ~102 ~40 black_concrete
fill ~0 ~102 ~40 ~12 ~102 ~40 brown_concrete
setblock ~13 ~102 ~40 black_concrete
setblock ~14 ~102 ~40 brown_concrete
setblock ~-17 ~101 ~40 brown_concrete
setblock ~-16 ~101 ~40 black_concrete
fill ~-15 ~101 ~40 ~12 ~101 ~40 brown_concrete
setblock ~13 ~101 ~40 black_concrete
setblock ~14 ~101 ~40 brown_concrete
setblock ~-18 ~100 ~40 brown_concrete
setblock ~-17 ~100 ~40 black_concrete
fill ~-16 ~100 ~40 ~13 ~100 ~40 brown_concrete
setblock ~14 ~100 ~40 black_concrete
setblock ~15 ~100 ~40 brown_concrete
setblock ~-18 ~99 ~40 brown_concrete
setblock ~-17 ~99 ~40 black_concrete
fill ~-16 ~99 ~40 ~-11 ~99 ~40 brown_concrete
fill ~-10 ~99 ~40 ~9 ~99 ~40 light_gray_concrete
fill ~10 ~99 ~40 ~13 ~99 ~40 brown_concrete
setblock ~14 ~99 ~40 black_concrete
setblock ~15 ~99 ~40 brown_concrete
setblock ~-18 ~98 ~40 brown_concrete
setblock ~-17 ~98 ~40 black_concrete
fill ~-16 ~98 ~40 ~-13 ~98 ~40 brown_concrete
fill ~-12 ~98 ~40 ~11 ~98 ~40 light_gray_concrete
fill ~12 ~98 ~40 ~13 ~98 ~40 brown_concrete
setblock ~14 ~98 ~40 black_concrete
setblock ~15 ~98 ~40 brown_concrete
setblock ~-18 ~97 ~40 brown_concrete
setblock ~-17 ~97 ~40 black_concrete
fill ~-16 ~97 ~40 ~-14 ~97 ~40 brown_concrete
fill ~-13 ~97 ~40 ~12 ~97 ~40 light_gray_concrete
setblock ~13 ~97 ~40 brown_concrete
setblock ~14 ~97 ~40 black_concrete
setblock ~15 ~97 ~40 brown_concrete
setblock ~-18 ~96 ~40 brown_concrete
setblock ~-17 ~96 ~40 black_concrete
fill ~-16 ~96 ~40 ~-15 ~96 ~40 brown_concrete
fill ~-14 ~96 ~40 ~-11 ~96 ~40 light_gray_concrete
fill ~-10 ~96 ~40 ~-9 ~96 ~40 white_concrete
fill ~-8 ~96 ~40 ~7 ~96 ~40 light_gray_concrete
fill ~8 ~96 ~40 ~9 ~96 ~40 white_concrete
fill ~10 ~96 ~40 ~12 ~96 ~40 light_gray_concrete
setblock ~13 ~96 ~40 brown_concrete
setblock ~14 ~96 ~40 black_concrete
setblock ~15 ~96 ~40 brown_concrete
setblock ~-18 ~95 ~40 brown_concrete
setblock ~-17 ~95 ~40 black_concrete
fill ~-16 ~95 ~40 ~-15 ~95 ~40 brown_concrete
fill ~-14 ~95 ~40 ~-12 ~95 ~40 light_gray_concrete
fill ~-11 ~95 ~40 ~-9 ~95 ~40 white_concrete
fill ~-8 ~95 ~40 ~6 ~95 ~40 light_gray_concrete
fill ~7 ~95 ~40 ~9 ~95 ~40 white_concrete
fill ~10 ~95 ~40 ~12 ~95 ~40 light_gray_concrete
setblock ~13 ~95 ~40 brown_concrete
setblock ~14 ~95 ~40 black_concrete
setblock ~15 ~95 ~40 brown_concrete
setblock ~-18 ~94 ~40 brown_concrete
setblock ~-17 ~94 ~40 black_concrete
fill ~-16 ~94 ~40 ~-15 ~94 ~40 brown_concrete
fill ~-14 ~94 ~40 ~12 ~94 ~40 light_gray_concrete
setblock ~13 ~94 ~40 brown_concrete
setblock ~14 ~94 ~40 black_concrete
setblock ~15 ~94 ~40 brown_concrete
setblock ~-18 ~93 ~40 brown_concrete
setblock ~-17 ~93 ~40 black_concrete
fill ~-16 ~93 ~40 ~-15 ~93 ~40 brown_concrete
fill ~-14 ~93 ~40 ~-13 ~93 ~40 light_gray_concrete
fill ~-12 ~93 ~40 ~-6 ~93 ~40 black_concrete
fill ~-5 ~93 ~40 ~2 ~93 ~40 light_gray_concrete
fill ~3 ~93 ~40 ~9 ~93 ~40 black_concrete
fill ~10 ~93 ~40 ~12 ~93 ~40 light_gray_concrete
setblock ~13 ~93 ~40 brown_concrete
setblock ~14 ~93 ~40 black_concrete
setblock ~15 ~93 ~40 brown_concrete
setblock ~-18 ~92 ~40 brown_concrete
setblock ~-17 ~92 ~40 black_concrete
fill ~-16 ~92 ~40 ~-15 ~92 ~40 brown_concrete
setblock ~-14 ~92 ~40 light_gray_concrete
fill ~-13 ~92 ~40 ~-5 ~92 ~40 black_concrete
fill ~-4 ~92 ~40 ~1 ~92 ~40 light_gray_concrete
fill ~2 ~92 ~40 ~10 ~92 ~40 black_concrete
fill ~11 ~92 ~40 ~12 ~92 ~40 light_gray_concrete
setblock ~13 ~92 ~40 brown_concrete
setblock ~14 ~92 ~40 black_concrete
setblock ~15 ~92 ~40 brown_concrete
setblock ~-18 ~91 ~40 brown_concrete
setblock ~-17 ~91 ~40 black_concrete
fill ~-16 ~91 ~40 ~-15 ~91 ~40 brown_concrete
fill ~-14 ~91 ~40 ~-13 ~91 ~40 light_gray_concrete
fill ~-12 ~91 ~40 ~-5 ~91 ~40 black_concrete
fill ~-4 ~91 ~40 ~2 ~91 ~40 light_gray_concrete
fill ~3 ~91 ~40 ~9 ~91 ~40 black_concrete
fill ~10 ~91 ~40 ~12 ~91 ~40 light_gray_concrete
setblock ~13 ~91 ~40 brown_concrete
setblock ~14 ~91 ~40 black_concrete
setblock ~15 ~91 ~40 brown_concrete
setblock ~-18 ~90 ~40 brown_concrete
setblock ~-17 ~90 ~40 black_concrete
fill ~-16 ~90 ~40 ~-15 ~90 ~40 brown_concrete
fill ~-14 ~90 ~40 ~12 ~90 ~40 light_gray_concrete
setblock ~13 ~90 ~40 brown_concrete
setblock ~14 ~90 ~40 black_concrete
setblock ~15 ~90 ~40 brown_concrete
setblock ~-18 ~89 ~40 brown_concrete
setblock ~-17 ~89 ~40 black_concrete
fill ~-16 ~89 ~40 ~-15 ~89 ~40 brown_concrete
fill ~-14 ~89 ~40 ~-12 ~89 ~40 light_gray_concrete
fill ~-11 ~89 ~40 ~-6 ~89 ~40 light_gray_wool
fill ~-5 ~89 ~40 ~3 ~89 ~40 light_gray_concrete
fill ~4 ~89 ~40 ~8 ~89 ~40 gray_concrete
fill ~9 ~89 ~40 ~12 ~89 ~40 light_gray_concrete
setblock ~13 ~89 ~40 brown_concrete
setblock ~14 ~89 ~40 black_concrete
setblock ~15 ~89 ~40 brown_concrete
setblock ~-18 ~88 ~40 brown_concrete
setblock ~-17 ~88 ~40 black_concrete
fill ~-16 ~88 ~40 ~-15 ~88 ~40 brown_concrete
fill ~-14 ~88 ~40 ~-13 ~88 ~40 light_gray_concrete
setblock ~-12 ~88 ~40 light_gray_wool
fill ~-11 ~88 ~40 ~-7 ~88 ~40 white_concrete
fill ~-6 ~88 ~40 ~-5 ~88 ~40 light_gray_wool
fill ~-4 ~88 ~40 ~2 ~88 ~40 light_gray_concrete
setblock ~3 ~88 ~40 gray_concrete
fill ~4 ~88 ~40 ~8 ~88 ~40 black_concrete
setblock ~9 ~88 ~40 gray_concrete
fill ~10 ~88 ~40 ~12 ~88 ~40 light_gray_concrete
setblock ~13 ~88 ~40 brown_concrete
setblock ~14 ~88 ~40 black_concrete
setblock ~15 ~88 ~40 brown_concrete
setblock ~-18 ~87 ~40 brown_concrete
setblock ~-17 ~87 ~40 black_concrete
fill ~-16 ~87 ~40 ~-15 ~87 ~40 brown_concrete
setblock ~-14 ~87 ~40 light_gray_concrete
setblock ~-13 ~87 ~40 light_gray_wool
fill ~-12 ~87 ~40 ~-11 ~87 ~40 white_concrete
fill ~-10 ~87 ~40 ~-8 ~87 ~40 black_concrete
fill ~-7 ~87 ~40 ~-6 ~87 ~40 white_concrete
setblock ~-5 ~87 ~40 light_gray_wool
fill ~-4 ~87 ~40 ~3 ~87 ~40 light_gray_concrete
fill ~4 ~87 ~40 ~8 ~87 ~40 gray_concrete
fill ~9 ~87 ~40 ~12 ~87 ~40 light_gray_concrete
setblock ~13 ~87 ~40 brown_concrete
setblock ~14 ~87 ~40 black_concrete
setblock ~15 ~87 ~40 brown_concrete
setblock ~-18 ~86 ~40 brown_concrete
setblock ~-17 ~86 ~40 black_concrete
fill ~-16 ~86 ~40 ~-15 ~86 ~40 brown_concrete
setblock ~-14 ~86 ~40 light_gray_concrete
setblock ~-13 ~86 ~40 light_gray_wool
setblock ~-12 ~86 ~40 white_concrete
fill ~-11 ~86 ~40 ~-7 ~86 ~40 black_concrete
setblock ~-6 ~86 ~40 white_concrete
setblock ~-5 ~86 ~40 light_gray_wool
fill ~-4 ~86 ~40 ~4 ~86 ~40 light_gray_concrete
fill ~5 ~86 ~40 ~7 ~86 ~40 light_gray_wool
fill ~8 ~86 ~40 ~12 ~86 ~40 light_gray_concrete
setblock ~13 ~86 ~40 brown_concrete
setblock ~14 ~86 ~40 black_concrete
setblock ~15 ~86 ~40 brown_concrete
setblock ~-18 ~85 ~40 brown_concrete
setblock ~-17 ~85 ~40 black_concrete
fill ~-16 ~85 ~40 ~-15 ~85 ~40 brown_concrete
setblock ~-14 ~85 ~40 light_gray_concrete
setblock ~-13 ~85 ~40 light_gray_wool
setblock ~-12 ~85 ~40 white_concrete
fill ~-11 ~85 ~40 ~-7 ~85 ~40 black_concrete
setblock ~-6 ~85 ~40 white_concrete
setblock ~-5 ~85 ~40 light_gray_wool
fill ~-4 ~85 ~40 ~12 ~85 ~40 light_gray_concrete
setblock ~13 ~85 ~40 brown_concrete
setblock ~14 ~85 ~40 black_concrete
setblock ~15 ~85 ~40 brown_concrete
setblock ~-18 ~84 ~40 brown_concrete
setblock ~-17 ~84 ~40 black_concrete
fill ~-16 ~84 ~40 ~-15 ~84 ~40 brown_concrete
setblock ~-14 ~84 ~40 light_gray_concrete
setblock ~-13 ~84 ~40 light_gray_wool
fill ~-12 ~84 ~40 ~-11 ~84 ~40 white_concrete
fill ~-10 ~84 ~40 ~-8 ~84 ~40 black_concrete
fill ~-7 ~84 ~40 ~-6 ~84 ~40 white_concrete
setblock ~-5 ~84 ~40 light_gray_wool
fill ~-4 ~84 ~40 ~12 ~84 ~40 light_gray_concrete
setblock ~13 ~84 ~40 brown_concrete
setblock ~14 ~84 ~40 black_concrete
setblock ~15 ~84 ~40 brown_concrete
setblock ~-18 ~83 ~40 brown_concrete
setblock ~-17 ~83 ~40 black_concrete
fill ~-16 ~83 ~40 ~-15 ~83 ~40 brown_concrete
fill ~-14 ~83 ~40 ~-13 ~83 ~40 light_gray_concrete
setblock ~-12 ~83 ~40 light_gray_wool
fill ~-11 ~83 ~40 ~-7 ~83 ~40 white_concrete
setblock ~-6 ~83 ~40 light_gray_wool
fill ~-5 ~83 ~40 ~12 ~83 ~40 light_gray_concrete
setblock ~13 ~83 ~40 brown_concrete
setblock ~14 ~83 ~40 black_concrete
setblock ~15 ~83 ~40 brown_concrete
setblock ~-18 ~82 ~40 brown_concrete
setblock ~-17 ~82 ~40 black_concrete
fill ~-16 ~82 ~40 ~-15 ~82 ~40 brown_concrete
fill ~-14 ~82 ~40 ~-12 ~82 ~40 light_gray_concrete
fill ~-11 ~82 ~40 ~-7 ~82 ~40 light_gray_wool
fill ~-6 ~82 ~40 ~12 ~82 ~40 light_gray_concrete
setblock ~13 ~82 ~40 brown_concrete
setblock ~14 ~82 ~40 black_concrete
setblock ~15 ~82 ~40 brown_concrete
setblock ~-18 ~81 ~40 brown_concrete
setblock ~-17 ~81 ~40 black_concrete
fill ~-16 ~81 ~40 ~-15 ~81 ~40 brown_concrete
fill ~-14 ~81 ~40 ~12 ~81 ~40 light_gray_concrete
setblock ~13 ~81 ~40 brown_concrete
setblock ~14 ~81 ~40 black_concrete
setblock ~15 ~81 ~40 brown_concrete
setblock ~-18 ~80 ~40 brown_concrete
setblock ~-17 ~80 ~40 black_concrete
fill ~-16 ~80 ~40 ~-15 ~80 ~40 brown_concrete
setblock ~-14 ~80 ~40 light_gray_wool
fill ~-13 ~80 ~40 ~11 ~80 ~40 light_gray_concrete
setblock ~12 ~80 ~40 light_gray_wool
setblock ~13 ~80 ~40 brown_concrete
setblock ~14 ~80 ~40 black_concrete
setblock ~15 ~80 ~40 brown_concrete
setblock ~-18 ~79 ~40 brown_concrete
setblock ~-17 ~79 ~40 black_concrete
fill ~-16 ~79 ~40 ~-15 ~79 ~40 brown_concrete
setblock ~-14 ~79 ~40 light_gray_wool
fill ~-13 ~79 ~40 ~-3 ~79 ~40 light_gray_concrete
fill ~-2 ~79 ~40 ~1 ~79 ~40 gray_concrete
fill ~2 ~79 ~40 ~11 ~79 ~40 light_gray_concrete
setblock ~12 ~79 ~40 light_gray_wool
setblock ~13 ~79 ~40 brown_concrete
setblock ~14 ~79 ~40 black_concrete
setblock ~15 ~79 ~40 brown_concrete
setblock ~-18 ~78 ~40 brown_concrete
setblock ~-17 ~78 ~40 black_concrete
fill ~-16 ~78 ~40 ~-15 ~78 ~40 brown_concrete
setblock ~-14 ~78 ~40 light_gray_wool
fill ~-13 ~78 ~40 ~-4 ~78 ~40 light_gray_concrete
fill ~-3 ~78 ~40 ~-2 ~78 ~40 gray_concrete
fill ~-1 ~78 ~40 ~0 ~78 ~40 light_gray_wool
fill ~1 ~78 ~40 ~2 ~78 ~40 gray_concrete
fill ~3 ~78 ~40 ~11 ~78 ~40 light_gray_concrete
setblock ~12 ~78 ~40 light_gray_wool
setblock ~13 ~78 ~40 brown_concrete
setblock ~14 ~78 ~40 black_concrete
setblock ~15 ~78 ~40 brown_concrete
setblock ~-18 ~77 ~40 brown_concrete
setblock ~-17 ~77 ~40 black_concrete
fill ~-16 ~77 ~40 ~-15 ~77 ~40 brown_concrete
setblock ~-14 ~77 ~40 light_gray_wool
fill ~-13 ~77 ~40 ~-4 ~77 ~40 light_gray_concrete
setblock ~-3 ~77 ~40 gray_concrete
fill ~-2 ~77 ~40 ~1 ~77 ~40 light_gray_wool
setblock ~2 ~77 ~40 gray_concrete
fill ~3 ~77 ~40 ~11 ~77 ~40 light_gray_concrete
setblock ~12 ~77 ~40 light_gray_wool
setblock ~13 ~77 ~40 brown_concrete
setblock ~14 ~77 ~40 black_concrete
setblock ~15 ~77 ~40 brown_concrete
setblock ~-18 ~76 ~40 brown_concrete
setblock ~-17 ~76 ~40 black_concrete
fill ~-16 ~76 ~40 ~-15 ~76 ~40 brown_concrete
setblock ~-14 ~76 ~40 light_gray_wool
fill ~-13 ~76 ~40 ~-5 ~76 ~40 light_gray_concrete
fill ~-4 ~76 ~40 ~-3 ~76 ~40 gray_concrete
fill ~-2 ~76 ~40 ~1 ~76 ~40 light_gray_wool
fill ~2 ~76 ~40 ~3 ~76 ~40 gray_concrete
fill ~4 ~76 ~40 ~11 ~76 ~40 light_gray_concrete
setblock ~12 ~76 ~40 light_gray_wool
setblock ~13 ~76 ~40 brown_concrete
setblock ~14 ~76 ~40 black_concrete
setblock ~15 ~76 ~40 brown_concrete
setblock ~-18 ~75 ~40 brown_concrete
setblock ~-17 ~75 ~40 black_concrete
fill ~-16 ~75 ~40 ~-15 ~75 ~40 brown_concrete
setblock ~-14 ~75 ~40 light_gray_wool
fill ~-13 ~75 ~40 ~-5 ~75 ~40 light_gray_concrete
setblock ~-4 ~75 ~40 gray_concrete
fill ~-3 ~75 ~40 ~2 ~75 ~40 light_gray_wool
setblock ~3 ~75 ~40 gray_concrete
fill ~4 ~75 ~40 ~11 ~75 ~40 light_gray_concrete
setblock ~12 ~75 ~40 light_gray_wool
setblock ~13 ~75 ~40 brown_concrete
setblock ~14 ~75 ~40 black_concrete
setblock ~15 ~75 ~40 brown_concrete
setblock ~-18 ~74 ~40 brown_concrete
setblock ~-17 ~74 ~40 black_concrete
fill ~-16 ~74 ~40 ~-15 ~74 ~40 brown_concrete
setblock ~-14 ~74 ~40 light_gray_wool
fill ~-13 ~74 ~40 ~-5 ~74 ~40 light_gray_concrete
setblock ~-4 ~74 ~40 gray_concrete
setblock ~-3 ~74 ~40 light_gray_wool
fill ~-2 ~74 ~40 ~1 ~74 ~40 gray_concrete
setblock ~2 ~74 ~40 light_gray_wool
setblock ~3 ~74 ~40 gray_concrete
fill ~4 ~74 ~40 ~11 ~74 ~40 light_gray_concrete
setblock ~12 ~74 ~40 light_gray_wool
setblock ~13 ~74 ~40 brown_concrete
setblock ~14 ~74 ~40 black_concrete
setblock ~15 ~74 ~40 brown_concrete
setblock ~-18 ~73 ~40 brown_concrete
setblock ~-17 ~73 ~40 black_concrete
fill ~-16 ~73 ~40 ~-15 ~73 ~40 brown_concrete
setblock ~-14 ~73 ~40 light_gray_wool
fill ~-13 ~73 ~40 ~-4 ~73 ~40 light_gray_concrete
fill ~-3 ~73 ~40 ~2 ~73 ~40 gray_concrete
fill ~3 ~73 ~40 ~11 ~73 ~40 light_gray_concrete
setblock ~12 ~73 ~40 light_gray_wool
setblock ~13 ~73 ~40 brown_concrete
setblock ~14 ~73 ~40 black_concrete
setblock ~15 ~73 ~40 brown_concrete
setblock ~-18 ~72 ~40 brown_concrete
setblock ~-17 ~72 ~40 black_concrete
fill ~-16 ~72 ~40 ~-15 ~72 ~40 brown_concrete
setblock ~-14 ~72 ~40 light_gray_wool
fill ~-13 ~72 ~40 ~11 ~72 ~40 light_gray_concrete
setblock ~12 ~72 ~40 light_gray_wool
setblock ~13 ~72 ~40 brown_concrete
setblock ~14 ~72 ~40 black_concrete
setblock ~15 ~72 ~40 brown_concrete
setblock ~-18 ~71 ~40 brown_concrete
setblock ~-17 ~71 ~40 black_concrete
fill ~-16 ~71 ~40 ~-15 ~71 ~40 brown_concrete
setblock ~-14 ~71 ~40 light_gray_wool
fill ~-13 ~71 ~40 ~11 ~71 ~40 light_gray_concrete
setblock ~12 ~71 ~40 light_gray_wool
setblock ~13 ~71 ~40 brown_concrete
setblock ~14 ~71 ~40 black_concrete
setblock ~15 ~71 ~40 brown_concrete
setblock ~-18 ~70 ~40 brown_concrete
setblock ~-17 ~70 ~40 black_concrete
fill ~-16 ~70 ~40 ~-15 ~70 ~40 brown_concrete
setblock ~-14 ~70 ~40 light_gray_wool
fill ~-13 ~70 ~40 ~-2 ~70 ~40 light_gray_concrete
fill ~-1 ~70 ~40 ~0 ~70 ~40 light_gray_wool
fill ~1 ~70 ~40 ~11 ~70 ~40 light_gray_concrete
setblock ~12 ~70 ~40 light_gray_wool
setblock ~13 ~70 ~40 brown_concrete
setblock ~14 ~70 ~40 black_concrete
setblock ~15 ~70 ~40 brown_concrete
setblock ~-18 ~69 ~40 brown_concrete
setblock ~-17 ~69 ~40 black_concrete
fill ~-16 ~69 ~40 ~-15 ~69 ~40 brown_concrete
setblock ~-14 ~69 ~40 light_gray_wool
fill ~-13 ~69 ~40 ~-6 ~69 ~40 light_gray_concrete
fill ~-5 ~69 ~40 ~-3 ~69 ~40 gray_concrete
fill ~-2 ~69 ~40 ~1 ~69 ~40 light_gray_wool
fill ~2 ~69 ~40 ~4 ~69 ~40 gray_concrete
fill ~5 ~69 ~40 ~11 ~69 ~40 light_gray_concrete
setblock ~12 ~69 ~40 light_gray_wool
setblock ~13 ~69 ~40 brown_concrete
setblock ~14 ~69 ~40 black_concrete
setblock ~15 ~69 ~40 brown_concrete
setblock ~-18 ~68 ~40 brown_concrete
setblock ~-17 ~68 ~40 black_concrete
fill ~-16 ~68 ~40 ~-15 ~68 ~40 brown_concrete
setblock ~-14 ~68 ~40 light_gray_wool
fill ~-13 ~68 ~40 ~-7 ~68 ~40 light_gray_concrete
setblock ~-6 ~68 ~40 gray_concrete
fill ~-5 ~68 ~40 ~-4 ~68 ~40 black_concrete
fill ~-3 ~68 ~40 ~2 ~68 ~40 gray_concrete
fill ~3 ~68 ~40 ~4 ~68 ~40 black_concrete
setblock ~5 ~68 ~40 gray_concrete
fill ~6 ~68 ~40 ~11 ~68 ~40 light_gray_concrete
setblock ~12 ~68 ~40 light_gray_wool
setblock ~13 ~68 ~40 brown_concrete
setblock ~14 ~68 ~40 black_concrete
setblock ~15 ~68 ~40 brown_concrete
setblock ~-18 ~67 ~40 brown_concrete
setblock ~-17 ~67 ~40 black_concrete
fill ~-16 ~67 ~40 ~-15 ~67 ~40 brown_concrete
setblock ~-14 ~67 ~40 light_gray_wool
fill ~-13 ~67 ~40 ~-6 ~67 ~40 light_gray_concrete
setblock ~-5 ~67 ~40 gray_concrete
fill ~-4 ~67 ~40 ~3 ~67 ~40 white_concrete
setblock ~4 ~67 ~40 gray_concrete
fill ~5 ~67 ~40 ~11 ~67 ~40 light_gray_concrete
setblock ~12 ~67 ~40 light_gray_wool
setblock ~13 ~67 ~40 brown_concrete
setblock ~14 ~67 ~40 black_concrete
setblock ~15 ~67 ~40 brown_concrete
setblock ~-18 ~66 ~40 brown_concrete
setblock ~-17 ~66 ~40 black_concrete
fill ~-16 ~66 ~40 ~-15 ~66 ~40 brown_concrete
setblock ~-14 ~66 ~40 light_gray_wool
fill ~-13 ~66 ~40 ~-5 ~66 ~40 light_gray_concrete
fill ~-4 ~66 ~40 ~-3 ~66 ~40 gray_concrete
fill ~-2 ~66 ~40 ~1 ~66 ~40 white_concrete
fill ~2 ~66 ~40 ~3 ~66 ~40 gray_concrete
fill ~4 ~66 ~40 ~11 ~66 ~40 light_gray_concrete
setblock ~12 ~66 ~40 light_gray_wool
setblock ~13 ~66 ~40 brown_concrete
setblock ~14 ~66 ~40 black_concrete
setblock ~15 ~66 ~40 brown_concrete
setblock ~-18 ~65 ~40 brown_concrete
setblock ~-17 ~65 ~40 black_concrete
fill ~-16 ~65 ~40 ~-15 ~65 ~40 brown_concrete
setblock ~-14 ~65 ~40 light_gray_wool
fill ~-13 ~65 ~40 ~-3 ~65 ~40 light_gray_concrete
fill ~-2 ~65 ~40 ~1 ~65 ~40 gray_concrete
fill ~2 ~65 ~40 ~11 ~65 ~40 light_gray_concrete
setblock ~12 ~65 ~40 light_gray_wool
setblock ~13 ~65 ~40 brown_concrete
setblock ~14 ~65 ~40 black_concrete
setblock ~15 ~65 ~40 brown_concrete
setblock ~-18 ~64 ~40 brown_concrete
setblock ~-17 ~64 ~40 black_concrete
fill ~-16 ~64 ~40 ~-15 ~64 ~40 brown_concrete
setblock ~-14 ~64 ~40 light_gray_wool
fill ~-13 ~64 ~40 ~11 ~64 ~40 light_gray_concrete
setblock ~12 ~64 ~40 light_gray_wool
setblock ~13 ~64 ~40 brown_concrete
setblock ~14 ~64 ~40 black_concrete
setblock ~15 ~64 ~40 brown_concrete
setblock ~-18 ~63 ~40 brown_concrete
setblock ~-17 ~63 ~40 black_concrete
fill ~-16 ~63 ~40 ~-15 ~63 ~40 brown_concrete
fill ~-14 ~63 ~40 ~-13 ~63 ~40 light_gray_wool
fill ~-12 ~63 ~40 ~10 ~63 ~40 light_gray_concrete
fill ~11 ~63 ~40 ~12 ~63 ~40 light_gray_wool
setblock ~13 ~63 ~40 brown_concrete
setblock ~14 ~63 ~40 black_concrete
setblock ~15 ~63 ~40 brown_concrete
setblock ~-18 ~62 ~40 brown_concrete
setblock ~-17 ~62 ~40 black_concrete
fill ~-16 ~62 ~40 ~-14 ~62 ~40 brown_concrete
fill ~-13 ~62 ~40 ~-12 ~62 ~40 light_gray_wool
fill ~-11 ~62 ~40 ~9 ~62 ~40 light_gray_concrete
fill ~10 ~62 ~40 ~11 ~62 ~40 light_gray_wool
fill ~12 ~62 ~40 ~13 ~62 ~40 brown_concrete
setblock ~14 ~62 ~40 black_concrete
setblock ~15 ~62 ~40 brown_concrete
setblock ~-17 ~61 ~40 brown_concrete
setblock ~-16 ~61 ~40 black_concrete
fill ~-15 ~61 ~40 ~-13 ~61 ~40 brown_concrete
fill ~-12 ~61 ~40 ~-11 ~61 ~40 light_gray_wool
fill ~-10 ~61 ~40 ~8 ~61 ~40 light_gray_concrete
fill ~9 ~61 ~40 ~10 ~61 ~40 light_gray_wool
fill ~11 ~61 ~40 ~12 ~61 ~40 brown_concrete
setblock ~13 ~61 ~40 black_concrete
setblock ~14 ~61 ~40 brown_concrete
setblock ~-16 ~60 ~40 brown_concrete
setblock ~-15 ~60 ~40 black_concrete
fill ~-14 ~60 ~40 ~-12 ~60 ~40 brown_concrete
fill ~-11 ~60 ~40 ~-9 ~60 ~40 light_gray_wool
fill ~-8 ~60 ~40 ~6 ~60 ~40 light_gray_concrete
fill ~7 ~60 ~40 ~9 ~60 ~40 light_gray_wool
fill ~10 ~60 ~40 ~11 ~60 ~40 brown_concrete
setblock ~12 ~60 ~40 black_concrete
setblock ~13 ~60 ~40 brown_concrete
setblock ~-15 ~59 ~40 brown_concrete
setblock ~-14 ~59 ~40 black_concrete
fill ~-13 ~59 ~40 ~-11 ~59 ~40 brown_concrete
fill ~-10 ~59 ~40 ~-8 ~59 ~40 light_gray_wool
fill ~-7 ~59 ~40 ~5 ~59 ~40 light_gray_concrete
fill ~6 ~59 ~40 ~8 ~59 ~40 light_gray_wool
fill ~9 ~59 ~40 ~11 ~59 ~40 brown_concrete
setblock ~12 ~59 ~40 black_concrete
setblock ~13 ~59 ~40 brown_concrete
setblock ~-14 ~58 ~40 brown_concrete
setblock ~-13 ~58 ~40 black_concrete
fill ~-12 ~58 ~40 ~-10 ~58 ~40 brown_concrete
fill ~-9 ~58 ~40 ~-6 ~58 ~40 light_gray_wool
fill ~-5 ~58 ~40 ~3 ~58 ~40 light_gray_concrete
fill ~4 ~58 ~40 ~7 ~58 ~40 light_gray_wool
fill ~8 ~58 ~40 ~10 ~58 ~40 brown_concrete
setblock ~11 ~58 ~40 black_concrete
setblock ~12 ~58 ~40 brown_concrete
setblock ~-13 ~57 ~40 brown_concrete
setblock ~-12 ~57 ~40 black_concrete
fill ~-11 ~57 ~40 ~-9 ~57 ~40 brown_concrete
fill ~-8 ~57 ~40 ~-4 ~57 ~40 light_gray_wool
fill ~-3 ~57 ~40 ~1 ~57 ~40 light_gray_concrete
fill ~2 ~57 ~40 ~6 ~57 ~40 light_gray_wool
fill ~7 ~57 ~40 ~9 ~57 ~40 brown_concrete
setblock ~10 ~57 ~40 black_concrete
setblock ~11 ~57 ~40 brown_concrete
setblock ~-12 ~56 ~40 brown_concrete
fill ~-11 ~56 ~40 ~-10 ~56 ~40 black_concrete
fill ~-9 ~56 ~40 ~-7 ~56 ~40 brown_concrete
fill ~-6 ~56 ~40 ~4 ~56 ~40 light_gray_wool
fill ~5 ~56 ~40 ~7 ~56 ~40 brown_concrete
fill ~8 ~56 ~40 ~9 ~56 ~40 black_concrete
setblock ~10 ~56 ~40 brown_concrete
fill ~-11 ~55 ~40 ~-10 ~55 ~40 brown_concrete
fill ~-9 ~55 ~40 ~-8 ~55 ~40 black_concrete
fill ~-7 ~55 ~40 ~-5 ~55 ~40 brown_concrete
fill ~-4 ~55 ~40 ~2 ~55 ~40 light_gray_wool
fill ~3 ~55 ~40 ~5 ~55 ~40 brown_concrete
fill ~6 ~55 ~40 ~7 ~55 ~40 black_concrete
fill ~8 ~55 ~40 ~9 ~55 ~40 brown_concrete
fill ~-10 ~54 ~40 ~-9 ~54 ~40 brown_concrete
fill ~-8 ~54 ~40 ~-7 ~54 ~40 black_concrete
fill ~-6 ~54 ~40 ~-4 ~54 ~40 brown_concrete
fill ~-3 ~54 ~40 ~1 ~54 ~40 light_gray_wool
fill ~2 ~54 ~40 ~4 ~54 ~40 brown_concrete
fill ~5 ~54 ~40 ~6 ~54 ~40 black_concrete
fill ~7 ~54 ~40 ~8 ~54 ~40 brown_concrete
fill ~-8 ~53 ~40 ~-7 ~53 ~40 brown_concrete
fill ~-6 ~53 ~40 ~-5 ~53 ~40 black_concrete
fill ~-4 ~53 ~40 ~-3 ~53 ~40 brown_concrete
fill ~-2 ~53 ~40 ~0 ~53 ~40 light_gray_wool
fill ~1 ~53 ~40 ~2 ~53 ~40 brown_concrete
fill ~3 ~53 ~40 ~4 ~53 ~40 black_concrete
fill ~5 ~53 ~40 ~6 ~53 ~40 brown_concrete
fill ~-6 ~52 ~40 ~-5 ~52 ~40 brown_concrete
setblock ~-4 ~52 ~40 black_concrete
fill ~-3 ~52 ~40 ~-2 ~52 ~40 brown_concrete
setblock ~-1 ~52 ~40 light_gray_wool
fill ~0 ~52 ~40 ~1 ~52 ~40 brown_concrete
setblock ~2 ~52 ~40 black_concrete
fill ~3 ~52 ~40 ~4 ~52 ~40 brown_concrete
setblock ~-4 ~51 ~40 brown_concrete
fill ~-3 ~51 ~40 ~1 ~51 ~40 black_concrete
setblock ~2 ~51 ~40 brown_concrete
fill ~-3 ~50 ~40 ~1 ~50 ~40 brown_concrete
